import { expect, test } from "vitest";
import backendModule from "../../../compiledBackend/backend.out";
import { sqrt } from "mathjs";
let backend = await backendModule();

// The following tests are generated by claude 4.8 opus (though I have verified them):

// Cross-gate relationship suite: identities that reference more than one gate.
// Single-gate period tests (X^2 = I, S^4 = I, T^8 = I) stay in the per-gate
// files; this file holds only the multi-gate identities.
//
// This suite assumes the per-gate suites already pass -- it is testing
// COMPOSITION and state-threading between gates, not re-checking each gate.
// A failure here with green per-gate suites points at how results thread
// between calls (marshalling/aliasing) or a cross-gate phase convention.
//
// toBeCloseTo(_, 9) is used throughout because H and T introduce sqrt(2)
// factors, so the composed results are not bit-exact.
//
// NOTE: hadamardGate is the confirmed name from the original suite; xGate,
// yGate, zGate, sGate, tGate are assumed -- adjust names/import path to your API.

// -----------------------------------------------------------------
// Gate wrappers: each turns a gate into a plain state -> state function,
// so identities can be written as ordinary nested function calls below.
// Fresh copies ({...s.alpha}) are passed in so a shared input state is never
// disturbed if a gate were to mutate its arguments.
// -----------------------------------------------------------------
const H = (s) => backend.hadamardGate({ ...s.alpha }, { ...s.beta });
const X = (s) => backend.XGate({ ...s.alpha }, { ...s.beta });
const Y = (s) => backend.YGate({ ...s.alpha }, { ...s.beta });
const Z = (s) => backend.ZGate({ ...s.alpha }, { ...s.beta });
const S = (s) => backend.SGate({ ...s.alpha }, { ...s.beta });
const T = (s) => backend.TGate({ ...s.alpha }, { ...s.beta });

// Apply a gate n times in a row: applyN(T, 4, s) is T(T(T(T(s)))).
// Used to express operator powers (S^2, T^4) without deep manual nesting.
function applyN(gate, n, s) {
  let r = s;
  for (let k = 0; k < n; k++) r = gate(r);
  return r;
}

// Some identities carry a global phase -- e.g. X Y equals Z times i, and
// H Y H equals Y times -1. timesI and negate apply that phase to a whole
// state so the right-hand side of the identity can be written out. These are
// plain complex arithmetic on the TEST side; they do not touch the gates.

// Multiply the whole state by i. For each amplitude, i*(a + bi) = -b + ai,
// so re/im swap and the new re is negated.
function timesI(s) {
  return {
    alpha: { re: -s.alpha.im, im: s.alpha.re },
    beta: { re: -s.beta.im, im: s.beta.re },
  };
}
// Multiply the whole state by -1 (negate both components of both amplitudes).
function negate(s) {
  return {
    alpha: { re: -s.alpha.re, im: -s.alpha.im },
    beta: { re: -s.beta.re, im: -s.beta.im },
  };
}

// Assert two states match amplitude-by-amplitude (all four real/imag
// components) to 9 digits -- close, not exact, because H and T make the
// composed values irrational and not bit-reproducible.
function expectSame(a, b) {
  expect(a.alpha.re).toBeCloseTo(b.alpha.re, 9);
  expect(a.alpha.im).toBeCloseTo(b.alpha.im, 9);
  expect(a.beta.re).toBeCloseTo(b.beta.re, 9);
  expect(a.beta.im).toBeCloseTo(b.beta.im, 9);
}

// The three input states each identity is checked on.
const psi0 = { alpha: { re: 1, im: 0 }, beta: { re: 0, im: 0 } }; // |0>
const psi1 = { alpha: { re: 0, im: 0 }, beta: { re: 1, im: 0 } }; // |1>
const psiG = {
  // A general state, all four components distinct and nonzero. |0> and |1>
  // already span the space (so they pin operator equality); this one also
  // catches non-linear bugs, e.g. a stray renormalization, that basis states
  // would slip past.
  alpha: { re: 1 / sqrt(30), im: -2 / sqrt(30) },
  beta: { re: -3 / sqrt(30), im: 4 / sqrt(30) },
};

// The core check. An operator identity is "left == right"; we hand each side
// in as a state -> state function:
//   left  = the composed gate sequence under test    (e.g. s => H(X(H(s))))
//   right = the operator it should equal, with any phase (e.g. s => timesI(Z(s)))
// Applying both to the same input and comparing outputs verifies the identity
// on that input; we repeat over |0>, |1>, and the general state.
//
// Reading the sequences: gates are nested calls, so the INNERMOST call runs
// first. H(X(H(s))) means "apply H, then X, then H" -- exactly the matrix
// product H X H acting on |psi> (right-to-left).
function checkIdentity(left, right) {
  for (const s of [psi0, psi1, psiG]) {
    expectSame(left(s), right(s));
  }
}

// ================================================================
// SECTION 1: Phase-gate ladder (diagonal powers)
// ================================================================

test("S^2 = Z", () => {
  // Applying the phase gate S twice equals a single Z.
  checkIdentity(
    (s) => applyN(S, 2, s),
    (s) => Z(s),
  );
});

test("T^2 = S", () => {
  // Two T (pi/4) phases compose into one S (pi/2) phase.
  checkIdentity(
    (s) => applyN(T, 2, s),
    (s) => S(s),
  );
});

test("T^4 = Z", () => {
  // Four T phases of pi/4 each add up to pi, which is Z.
  checkIdentity(
    (s) => applyN(T, 4, s),
    (s) => Z(s),
  );
});

// ================================================================
// SECTION 2: Hadamard conjugations
// ================================================================

test("H X H = Z", () => {
  // Conjugating X by Hadamard turns it into Z.
  // Left side, innermost-first: apply H, then X, then H.
  checkIdentity(
    (s) => H(X(H(s))),
    (s) => Z(s),
  );
});

test("H Z H = X", () => {
  // The mirror image: conjugating Z by Hadamard gives back X.
  checkIdentity(
    (s) => H(Z(H(s))),
    (s) => X(s),
  );
});

test("H Y H = -Y", () => {
  // Conjugating Y by Hadamard flips its sign, so the target is -Y.
  // negate() supplies that factor of -1 on the right-hand side.
  checkIdentity(
    (s) => H(Y(H(s))),
    (s) => negate(Y(s)),
  );
});

// ================================================================
// SECTION 3: Pauli products
// ================================================================

test("X Y = i Z", () => {
  // Product of two Paulis: X after Y equals Z, up to a global phase of i.
  // Left: apply Y, then X. Right: i times Z, supplied by timesI().
  checkIdentity(
    (s) => X(Y(s)),
    (s) => timesI(Z(s)),
  );
});

test("Y Z = i X", () => {
  // Apply Z, then Y; equals i times X.
  checkIdentity(
    (s) => Y(Z(s)),
    (s) => timesI(X(s)),
  );
});

test("Z X = i Y", () => {
  // Apply X, then Z; equals i times Y.
  checkIdentity(
    (s) => Z(X(s)),
    (s) => timesI(Y(s)),
  );
});
