import { expect, test } from "vitest";
import backendModule from "../../../compiledBackend/backend.out";
import { sqrt } from "mathjs";
let backend = await backendModule();
// The following tests are generated by claude 4.8 opus (though I have verified them):

// S = [[1, 0], [0, i]], so alpha' = alpha (unchanged) and beta' = i * beta.
// Like Z it is diagonal (no swap), but the phase on beta is i rather than -1.
// Multiplying by i is a reshuffle-and-negate of beta's components
// (i*(a+bi) = -b + ai), so it is still exact and these use toBe.
//
// S is NOT its own inverse: S^2 = Z and S^4 = I. The self-consistency test
// below therefore applies S four times (not twice) to recover the input.
// The S^2 = Z relationship is intentionally left for the cross-gate
// relationship suite, so this file only ever references S and the identity.

// ================================================================
// SECTION 1: Basis states (defining behavior / eigenstates)
// ================================================================

test("results are as expected for the |0> basis state (1, 0)", () => {
  const result = backend.SGate({ re: 1, im: 0 }, { re: 0, im: 0 });
  // S|0> = |0> (the +1 eigenstate): nothing changes
  // Alpha should stay 1
  expect(result.alpha.re).toBe(1);
  expect(result.alpha.im).toBe(0);
  // Beta should stay 0
  expect(result.beta.re).toBe(0);
  expect(result.beta.im).toBe(0);
});

test("results are as expected for the |1> basis state (0, 1)", () => {
  const result = backend.SGate({ re: 0, im: 0 }, { re: 1, im: 0 });
  // S|1> = i|1>: beta picks up a factor of i (0 + 1i). This distinguishes S
  // from Z, which would send beta to -1 (real) instead.
  // Alpha should stay 0
  expect(result.alpha.re).toBe(0);
  expect(result.alpha.im).toBe(0);
  // Beta should become i (0 + 1i)
  expect(result.beta.re).toBe(0);
  expect(result.beta.im).toBe(1);
});

// ================================================================
// SECTION 2: General behavior
// ================================================================

test("results are as expected for a real superposition (0.6, 0.8)", () => {
  const result = backend.SGate({ re: 0.6, im: 0 }, { re: 0.8, im: 0 });
  // Alpha unchanged; beta rotates from real to imaginary: i * 0.8 = 0.8i
  // Alpha should stay 0.6
  expect(result.alpha.re).toBe(0.6);
  expect(result.alpha.im).toBe(0);
  // Beta should become 0.8i
  expect(result.beta.re).toBe(0);
  expect(result.beta.im).toBe(0.8);
});

test("results are as expected for a general complex state with mixed signs ((1 - 2i)/sqrt(30), (-3 + 4i)/sqrt(30))", () => {
  const result = backend.SGate(
    { re: 1 / sqrt(30), im: -2 / sqrt(30) },
    { re: -3 / sqrt(30), im: 4 / sqrt(30) },
  );
  // alpha' = alpha    = (1 - 2i)/sqrt(30)               (passes through unchanged)
  // beta'  = i * beta = i * (-3 + 4i)/sqrt(30) = (-4 - 3i)/sqrt(30)
  // Alpha must be untouched while beta's real and imaginary parts reshuffle
  // with the correct signs, so touching alpha, a wrong phase direction, a
  // conjugation, or a swap all surface here.
  // Alpha should stay (1 - 2i)/sqrt(30)
  expect(result.alpha.re).toBe(1 / sqrt(30));
  expect(result.alpha.im).toBe(-2 / sqrt(30));
  // Beta should become (-4 - 3i)/sqrt(30)
  expect(result.beta.re).toBe(-4 / sqrt(30));
  expect(result.beta.im).toBe(-3 / sqrt(30));
});

// ================================================================
// SECTION 3: Edge cases
// ================================================================

test("results are as expected for purely imaginary amplitudes (i/sqrt(2), i/sqrt(2))", () => {
  const result = backend.SGate(
    { re: 0, im: 1 / sqrt(2) },
    { re: 0, im: 1 / sqrt(2) },
  );
  // Alpha (imaginary) passes through untouched; beta rotates:
  // i * (i/sqrt(2)) = i^2 / sqrt(2) = -1/sqrt(2), imaginary turning real negative.
  // A wrong phase sign would give +1/sqrt(2) here instead.
  // Alpha should stay i/sqrt(2)
  expect(result.alpha.re).toBe(0);
  expect(result.alpha.im).toBe(1 / sqrt(2));
  // Beta should become -1/sqrt(2)
  expect(result.beta.re).toBe(-1 / sqrt(2));
  expect(result.beta.im).toBe(0);
});

test("applying S four times returns the original state (S^4 = I)", () => {
  // S is period-4: beta picks up i each time and i^4 = 1, so four applications
  // restore beta while alpha never changes. (Two applications would give Z.)
  const startAlpha = { re: 0.5, im: 0.5 };
  const startBeta = { re: 0.5, im: -0.5 };
  let r = backend.SGate(startAlpha, startBeta);
  r = backend.SGate(r.alpha, r.beta);
  r = backend.SGate(r.alpha, r.beta);
  r = backend.SGate(r.alpha, r.beta);
  // Alpha should return to 0.5 + 0.5i
  expect(r.alpha.re).toBe(startAlpha.re);
  expect(r.alpha.im).toBe(startAlpha.im);
  // Beta should return to 0.5 - 0.5i
  expect(r.beta.re).toBe(startBeta.re);
  expect(r.beta.im).toBe(startBeta.im);
});
