import { expect, test } from "vitest";
import backendModule from "../../../compiledBackend/backend.out";
import { sqrt } from "mathjs";
let backend = await backendModule();
// The following tests are generated by claude 4.8 opus (though I have verified them):

// T = [[1, 0], [0, e^{i pi/4}]], with e^{i pi/4} = (1 + i)/sqrt(2). So
// alpha' = alpha (unchanged) and beta' = (1 + i)/sqrt(2) * beta, which works
// out to beta' = ((beta.re - beta.im) + (beta.re + beta.im) i) / sqrt(2).
//
// T is the first gate that actually combines the input components rather than
// shuffling them. beta' = (1 + i)/sqrt(2) * beta computes (beta.re - beta.im)/sqrt(2):
// a subtraction of two irrationals followed by a fresh division, producing a value
// that never existed in the input. Its low bits depend on the backend's exact
// evaluation path (e.g. whether the phase is a cos/sin constant), which need not
// match how the expected value rounds when calculating here on the frontend -- hence
// toBeCloseTo rather than toBe.
//
// So this file splits its assertions -- alpha still passes through untouched and uses toBe,
// but beta uses toBeCloseTo(_, 9). Do NOT "fix" a beta assertion by tightening it to
// toBe: beta is expected to be inexact here.
//
// T is period-8: T^2 = S, T^4 = Z, T^8 = I. The self-consistency test applies
// T eight times to recover the input; the T^2 = S and T^4 = Z relationships
// are left for the cross-gate relationship suite, so this file only ever
// references T and the identity.

// ================================================================
// SECTION 1: Basis states (defining behavior / eigenstates)
// ================================================================

test("results are as expected for the |0> basis state (1, 0)", () => {
  const result = backend.TGate({ re: 1, im: 0 }, { re: 0, im: 0 });
  // T|0> = |0> (the +1 eigenstate): nothing changes. beta stays exactly 0
  // because the phase multiplies zero.
  // Alpha should stay 1
  expect(result.alpha.re).toBe(1);
  expect(result.alpha.im).toBe(0);
  // Beta should stay 0
  expect(result.beta.re).toBe(0);
  expect(result.beta.im).toBe(0);
});

test("results are as expected for the |1> basis state (0, 1)", () => {
  const result = backend.TGate({ re: 0, im: 0 }, { re: 1, im: 0 });
  // T|1> = e^{i pi/4}|1> = (1 + i)/sqrt(2) (equivalent). This pins the phase and
  // distinguishes T from S (which would send beta to i) and Z (to -1).
  // Alpha should stay 0 (exact)
  expect(result.alpha.re).toBe(0);
  expect(result.alpha.im).toBe(0);
  // Beta should become (1 + i)/sqrt(2)
  expect(result.beta.re).toBeCloseTo(1 / sqrt(2), 9);
  expect(result.beta.im).toBeCloseTo(1 / sqrt(2), 9);
});

// ================================================================
// SECTION 2: General behavior
// ================================================================

test("results are as expected for a real superposition (0.6, 0.8)", () => {
  const result = backend.TGate({ re: 0.6, im: 0 }, { re: 0.8, im: 0 });
  // Alpha unchanged; a real beta rotates 45 degrees to equal re/im parts:
  // beta' = (1 + i)/sqrt(2) * 0.8 = (0.8 + 0.8i)/sqrt(2)
  // Alpha should stay 0.6 (exact)
  expect(result.alpha.re).toBe(0.6);
  expect(result.alpha.im).toBe(0);
  // Beta should become (0.8 + 0.8i)/sqrt(2)
  expect(result.beta.re).toBeCloseTo(0.8 / sqrt(2), 9);
  expect(result.beta.im).toBeCloseTo(0.8 / sqrt(2), 9);
});

test("results are as expected for a general complex state with mixed signs ((1 - 2i)/sqrt(30), (-3 + 4i)/sqrt(30))", () => {
  // save these for later
  const bRe = -3 / sqrt(30);
  const bIm = 4 / sqrt(30);
  const result = backend.TGate(
    { re: 1 / sqrt(30), im: -2 / sqrt(30) },
    { re: bRe, im: bIm },
  );
  // alpha' = alpha = (1 - 2i)/sqrt(30), untouched and exact.
  // beta'  = (1 + i)/sqrt(2) * beta
  //        = ((bRe - bIm) + (bRe + bIm) i)/sqrt(2) = (-7 + i)/sqrt(60)
  // The two combined channels (bRe - bIm and bRe + bIm) mean a wrong phase
  // direction, a conjugation, touching alpha, or a swap all surface here.
  // Alpha should stay (1 - 2i)/sqrt(30) (exact)
  expect(result.alpha.re).toBe(1 / sqrt(30));
  expect(result.alpha.im).toBe(-2 / sqrt(30));
  // Beta should become (-7 + i)/sqrt(60)
  expect(result.beta.re).toBeCloseTo(-7 / sqrt(60), 9);
  expect(result.beta.im).toBeCloseTo(1 / sqrt(60), 9);
});

// ================================================================
// SECTION 3: Edge cases
// ================================================================

test("results are as expected for purely imaginary amplitudes (i/sqrt(2), i/sqrt(2))", () => {
  const result = backend.TGate(
    { re: 0, im: 1 / sqrt(2) },
    { re: 0, im: 1 / sqrt(2) },
  );
  // Alpha (imaginary) passes through untouched. beta = i/sqrt(2) rotates:
  // (1 + i)/sqrt(2) * (i/sqrt(2)) = (i - 1)/2 = (-1 + i)/2 = -0.5 + 0.5i.
  // Alpha should stay i/sqrt(2) (exact passthrough)
  expect(result.alpha.re).toBe(0);
  expect(result.alpha.im).toBe(1 / sqrt(2));
  // Beta should become -0.5 + 0.5i
  expect(result.beta.re).toBeCloseTo(-0.5, 9);
  expect(result.beta.im).toBeCloseTo(0.5, 9);
});

test("applying T eight times returns the original state (T^8 = I)", () => {
  // T is period-8: beta picks up e^{i pi/4} each time and (e^{i pi/4})^8 = 1.
  // Alpha is never modified, so it stays exact; beta accumulates eight rounds
  // of floating point but stays far within 9 digits.
  const startAlpha = { re: 0.5, im: 0.5 };
  const startBeta = { re: 0.5, im: -0.5 };
  let r = backend.TGate(startAlpha, startBeta);
  for (let n = 0; n < 7; n++) {
    r = backend.TGate(r.alpha, r.beta);
  }
  // Alpha is untouched, so it returns exactly
  expect(r.alpha.re).toBe(startAlpha.re);
  expect(r.alpha.im).toBe(startAlpha.im);
  // Beta returns to 0.5 - 0.5i within 9 digits
  expect(r.beta.re).toBeCloseTo(startBeta.re, 9);
  expect(r.beta.im).toBeCloseTo(startBeta.im, 9);
});
