import { afterAll, expect, test } from "vitest";
import { readFileSync } from "node:fs";
import { maxComponentDiff } from "./stateCompare";
import backendModule from "../../../compiledBackend/backend.out";
let backend = await backendModule();

// The following test was generated by opus 4.8 and validated by me.

// ================================================================
// Qiskit cross-check: replay each recorded sequence through the backend and
// compare to Qiskit's per-step reference. This is the one suite whose oracle
// you did NOT write, so it can catch a shared-mental-model error that the
// hand-written per-gate tests cannot.
//
// ================================================================

// ----------------------------------------------------------------
// SECTION 1: Load the fixture produced by generate_qiskit_reference.py.
// Read via fs (not a JSON import) to avoid Node's import-assertion churn.
// The file is assumed to sit next to this test -- adjust the URL if not.
// ----------------------------------------------------------------
const FIXTURE_PATH = new URL("./gate_reference.json", import.meta.url);
let fixture;
try {
  fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf8"));
} catch (e) {
  throw new Error(
    `Could not load gate_reference.json at ${FIXTURE_PATH}.\n` +
      `Generate it first:  python generate_qiskit_reference.py --out gate_reference.json\n` +
      `(${e.message})`,
  );
}

const sequences = fixture.sequences;
const TOLERANCE = fixture.meta.tolerance_hint ?? 1e-10;

// ----------------------------------------------------------------
// SECTION 2: Gate dispatch. Map each fixture gate name to a state -> state
// call on the backend. Fresh copies are passed in so a reused input object is
// never disturbed if a gate mutates its arguments. This is the ONLY place the
// fixture's "H"/"X"/... strings meet your backend methods.
// ----------------------------------------------------------------
const GATES = {
  H: (s) => backend.hadamardGate({ ...s.alpha }, { ...s.beta }),
  X: (s) => backend.XGate({ ...s.alpha }, { ...s.beta }),
  Y: (s) => backend.YGate({ ...s.alpha }, { ...s.beta }),
  Z: (s) => backend.ZGate({ ...s.alpha }, { ...s.beta }),
  S: (s) => backend.SGate({ ...s.alpha }, { ...s.beta }),
  T: (s) => backend.TGate({ ...s.alpha }, { ...s.beta }),
};

// ----------------------------------------------------------------
// SECTION 3: Comparison + running max deviation.
// deviation = the largest absolute difference across the four real components.
// This assumes no global-phase offset between backend and Qiskit, which holds
// for these six standard gates. (If you later add gates with a phase
// convention, e.g. RZ, switch to a phase-invariant metric like |<psi|phi>|.)
// maxDeviation/comparisons accumulate across every step of every sequence so
// the afterAll hook can report the real agreement figure.
// ----------------------------------------------------------------
let maxDeviation = 0;
let comparisons = 0;

function deviation(got, expected) {
  const d = maxComponentDiff(got, expected); // was the inline Math.max(...)
  comparisons++;
  if (d > maxDeviation) maxDeviation = d;
  return d;
}

// TODO: magic function, make clear what it does.
const fmt = (s) => {
  const c = (z) =>
    `${z.re.toFixed(6)}${z.im >= 0 ? "+" : "-"}${Math.abs(z.im).toFixed(6)}i`;
  return `alpha=${c(s.alpha)} beta=${c(s.beta)}`;
};

// ----------------------------------------------------------------
// SECTION 4: Replay a sequence step by step. Start from the recorded input,
// apply each gate through the backend, and compare to Qiskit AFTER every gate.
// Returns the FIRST step that exceeds tolerance (localization) or ok:true.
// ----------------------------------------------------------------
function replay(seq) {
  let state = seq.input;
  for (const step of seq.steps) {
    state = GATES[step.gate](state);
    const expected = { alpha: step.alpha, beta: step.beta };
    const d = deviation(state, expected);
    if (d > TOLERANCE) {
      return { ok: false, step, d, got: state, expected };
    }
  }
  return { ok: true };
}

function assertReplay(seq) {
  const r = replay(seq);
  if (!r.ok) {
    throw new Error(
      `seq #${seq.id} diverged at step ${r.step.index} (gate ${r.step.gate}) ` +
        `of [${seq.gates.join(" ")}]\n` +
        `  deviation ${r.d.toExponential(3)} > tolerance ${TOLERANCE}\n` +
        `  got:      ${fmt(r.got)}\n` +
        `  expected: ${fmt(r.expected)}`,
    );
  }
  expect(r.ok).toBe(true);
}

const label = (s) => {
  const g = s.gates.length <= 8 ? s.gates.join("") : `${s.gates.length}gates`;
  return `#${s.id} ${s.kind} (${g})`;
};

// ----------------------------------------------------------------
// SECTION 5: Sanity guard on the fixture itself (independent of the backend).
// Confirms the JSON loaded and that we are reading amps[0] as alpha: H|0>
// must be recorded as (1/sqrt(2), 1/sqrt(2)). If the convention were flipped
// this fails before any backend comparison muddies the picture.
// ----------------------------------------------------------------
test("fixture loads and the alpha/beta convention is sane", () => {
  expect(sequences.length).toBeGreaterThan(0);
  const hOn0 = sequences.find(
    (s) =>
      s.kind === "sanity" &&
      s.gates.length === 1 &&
      s.gates[0] === "H" &&
      s.input.alpha.re === 1 &&
      s.input.beta.re === 0,
  );
  expect(hOn0).toBeDefined();
  const out = hOn0.steps[0];
  expect(out.alpha.re).toBeCloseTo(Math.SQRT1_2, 12);
  expect(out.alpha.im).toBeCloseTo(0, 12);
  expect(out.beta.re).toBeCloseTo(Math.SQRT1_2, 12);
  expect(out.beta.im).toBeCloseTo(0, 12);
});

// ----------------------------------------------------------------
// SECTION 6: Sanity sequences -- each gate once on |0> and |1>. If a single
// gate's convention is off, it shows here at length 1 rather than buried in a
// long chain.
// ----------------------------------------------------------------
const sanitySequences = sequences.filter((s) => s.kind === "sanity");

test.each(sanitySequences.map((s) => [label(s), s]))(
  "sanity %s matches Qiskit at every step",
  (_lbl, seq) => assertReplay(seq),
);

// ----------------------------------------------------------------
// SECTION 7: Random sequences. Scoped to the first few while we confirm the
// approach. To run the full set, raise REVIEW_LIMIT to Infinity (or delete the
// slice) -- no other change needed; the harness above already handles all of
// them, including per-step localization and the deviation report.
// ----------------------------------------------------------------
const randomSequences = sequences.filter((s) => s.kind === "random");

test.each(randomSequences.map((s) => [label(s), s]))(
  "random %s matches Qiskit at every step",
  (_lbl, seq) => assertReplay(seq),
);

// ----------------------------------------------------------------
// SECTION 8: Report the actual maximum deviation observed. THIS is the honest
// number for the resume bullet -- likely ~1e-14, far tighter than the 1e-10
// assertion threshold.
// ----------------------------------------------------------------
afterAll(() => {
  console.log(
    `\n[Qiskit cross-check] compared ${comparisons} states across ` +
      `${sanitySequences.length + randomSequences.length} sequences; ` +
      `max deviation = ${maxDeviation.toExponential(3)} ` +
      `(assertion threshold ${TOLERANCE}).`,
  );
});

// Pure comparison metric shared by the Qiskit cross-check (QiskitReference_test.js)
// and its unit test (stateCompare.test.js). Deliberately side-effect-free so it
// can be exercised in isolation; the running-max tracking the cross-check needs
// lives in that test file, wrapped around this.
//
// A state is { alpha: { re, im }, beta: { re, im } }.

// Largest absolute difference across the four real components of two states.
// Component-wise (not fidelity), so it is phase-SENSITIVE: two states that are
// equal up to a global phase register as different. That is intended for the six
// standard gates (no phase-convention offset vs Qiskit); revisit this metric if
// phase-carrying gates like RZ are ever added.
export function maxComponentDiff(a, b) {
  return Math.max(
    Math.abs(a.alpha.re - b.alpha.re),
    Math.abs(a.alpha.im - b.alpha.im),
    Math.abs(a.beta.re - b.beta.re),
    Math.abs(a.beta.im - b.beta.im),
  );
}
