import { expect, test } from "vitest";
import backendModule from "../../../compiledBackend/backend.out";
import { sqrt } from "mathjs";
let backend = await backendModule();

// The other gates have significantly fewer tests than hadamard test does, since I went a little overboard there.

// The following tests are generated by claude 4.8 opus (though I have verified them):

// ================================================================
// SECTION 1: Basis states (defining behavior)
// ================================================================

test("results are as expected for the |0> basis state (1, 0)", () => {
  const result = backend.XGate({ re: 1, im: 0 }, { re: 0, im: 0 });
  // |0> should become |1>
  // Alpha should become 0
  expect(result.alpha.re).toBe(0);
  expect(result.alpha.im).toBe(0);
  // Beta should become 1
  expect(result.beta.re).toBe(1);
  expect(result.beta.im).toBe(0);
});

test("results are as expected for the |1> basis state (0, 1)", () => {
  const result = backend.XGate({ re: 0, im: 0 }, { re: 1, im: 0 });
  // |1> should become |0>
  // Alpha should become 1
  expect(result.alpha.re).toBe(1);
  expect(result.alpha.im).toBe(0);
  // Beta should become 0
  expect(result.beta.re).toBe(0);
  expect(result.beta.im).toBe(0);
});

// ================================================================
// SECTION 2: General swap behavior
// ================================================================

test("results are as expected for a real superposition (0.6, 0.8)", () => {
  const result = backend.XGate({ re: 0.6, im: 0 }, { re: 0.8, im: 0 });
  // Two nonzero real amplitudes swap places
  // Alpha should become 0.8
  expect(result.alpha.re).toBe(0.8);
  expect(result.alpha.im).toBe(0);
  // Beta should become 0.6
  expect(result.beta.re).toBe(0.6);
  expect(result.beta.im).toBe(0);
});

test("results are as expected for a general complex state with mixed signs ((1 - 2i)/sqrt(30), (-3 + 4i)/sqrt(30))", () => {
  const result = backend.XGate(
    { re: 1 / sqrt(30), im: -2 / sqrt(30) },
    { re: -3 / sqrt(30), im: 4 / sqrt(30) },
  );
  // X swaps the amplitudes exactly, carrying every sign with them. All four
  // components are distinct and nonzero, with both a negative real and a
  // negative imaginary part, so a partial swap (re-only or im-only), a field
  // swap (re <-> im within an amplitude), a stray conjugation, a real or
  // imaginary sign flip, or a copy-instead-of-swap all surface here.
  // Alpha should become the old beta: (-3 + 4i)/sqrt(30)
  expect(result.alpha.re).toBe(-3 / sqrt(30));
  expect(result.alpha.im).toBe(4 / sqrt(30));
  // Beta should become the old alpha: (1 - 2i)/sqrt(30)
  expect(result.beta.re).toBe(1 / sqrt(30));
  expect(result.beta.im).toBe(-2 / sqrt(30));
});

// ================================================================
// SECTION 3: Edge cases
// ================================================================

test("results are as expected for a purely imaginary amplitude (i, 0)", () => {
  const result = backend.XGate({ re: 0, im: 1 }, { re: 0, im: 0 });
  // Swaps to (0, i). The re = 0 amplitude exercises a distinct path: a field
  // swap bug would surface here as i turning into 1.
  // Alpha should become 0
  expect(result.alpha.re).toBe(0);
  expect(result.alpha.im).toBe(0);
  // Beta should become i
  expect(result.beta.re).toBe(0);
  expect(result.beta.im).toBe(1);
});

test("applying X twice returns the original state (involution)", () => {
  // X * X = I. Uses a fully complex state so both channels and both
  // components are exercised; two swaps return the exact original doubles.
  const startAlpha = { re: 0.5, im: 0.5 };
  const startBeta = { re: 0.5, im: -0.5 };
  const once = backend.XGate(startAlpha, startBeta);
  const twice = backend.XGate(once.alpha, once.beta);
  // Alpha should return to 0.5 + 0.5i
  expect(twice.alpha.re).toBe(startAlpha.re);
  expect(twice.alpha.im).toBe(startAlpha.im);
  // Beta should return to 0.5 - 0.5i
  expect(twice.beta.re).toBe(startBeta.re);
  expect(twice.beta.im).toBe(startBeta.im);
});
