import { expect, test } from "vitest";
import backendModule from "../../../compiledBackend/backend.out";
import { sqrt } from "mathjs";
let backend = await backendModule();

// The following tests are generated by claude 4.8 opus (though I have verified them):

// Y = [[0, -i], [i, 0]], so alpha' = -i * beta and beta' = i * alpha.
// Unlike X, Y applies a phase: multiplying by +/- i rotates each amplitude
// 90 degrees, sending real parts to imaginary and vice versa (with a sign).
// That multiplication is still only a reshuffle-and-negate of the input
// components, so each output stays bit-identical to +/- an input component.

// ================================================================
// SECTION 1: Basis states (defining behavior, including the phase)
// ================================================================

test("results are as expected for the |0> basis state (1, 0)", () => {
  const result = backend.YGate({ re: 1, im: 0 }, { re: 0, im: 0 });
  // Y|0> = i|1>: alpha cancels, beta picks up +i
  // Alpha should become 0
  expect(result.alpha.re).toBe(0);
  expect(result.alpha.im).toBe(0);
  // Beta should become i (0 + 1i)
  expect(result.beta.re).toBe(0);
  expect(result.beta.im).toBe(1);
});

test("results are as expected for the |1> basis state (0, 1)", () => {
  const result = backend.YGate({ re: 0, im: 0 }, { re: 1, im: 0 });
  // Y|1> = -i|0>: alpha picks up -i, beta cancels
  // Alpha should become -i (0 - 1i)
  expect(result.alpha.re).toBe(0);
  expect(result.alpha.im).toBe(-1);
  // Beta should become 0
  expect(result.beta.re).toBe(0);
  expect(result.beta.im).toBe(0);
});

// ================================================================
// SECTION 2: General behavior
// ================================================================

test("results are as expected for a real superposition (0.6, 0.8)", () => {
  const result = backend.YGate({ re: 0.6, im: 0 }, { re: 0.8, im: 0 });
  // Real inputs rotate to purely imaginary outputs:
  // alpha' = -i * 0.8 = -0.8i, beta' = i * 0.6 = 0.6i
  // Alpha should become -0.8i
  expect(result.alpha.re).toBe(0);
  expect(result.alpha.im).toBe(-0.8);
  // Beta should become 0.6i
  expect(result.beta.re).toBe(0);
  expect(result.beta.im).toBe(0.6);
});

test("results are as expected for a general complex state with mixed signs ((1 - 2i)/sqrt(30), (-3 + 4i)/sqrt(30))", () => {
  const result = backend.YGate(
    { re: 1 / sqrt(30), im: -2 / sqrt(30) },
    { re: -3 / sqrt(30), im: 4 / sqrt(30) },
  );
  // alpha' = -i * beta  = -i * (-3 + 4i)/sqrt(30) = (4 + 3i)/sqrt(30)
  // beta'  =  i * alpha =  i * (1 - 2i)/sqrt(30)  = (2 + 1i)/sqrt(30)
  // Both re/im channels and every sign are exercised at once, so a wrong
  // phase sign, a partial swap, a field swap, or a conjugation all surface.
  // Alpha should become (4 + 3i)/sqrt(30)
  expect(result.alpha.re).toBe(4 / sqrt(30));
  expect(result.alpha.im).toBe(3 / sqrt(30));
  // Beta should become (2 + 1i)/sqrt(30)
  expect(result.beta.re).toBe(2 / sqrt(30));
  expect(result.beta.im).toBe(1 / sqrt(30));
});

// ================================================================
// SECTION 3: Edge cases
// ================================================================

test("results are as expected for a purely imaginary amplitude (i, 0)", () => {
  const result = backend.YGate({ re: 0, im: 1 }, { re: 0, im: 0 });
  // beta' = i * alpha = i * i = -1: an imaginary amplitude rotates to a real
  // (negative) one. A sign or conjugation bug would give +1 here instead.
  // Alpha should become 0
  expect(result.alpha.re).toBe(0);
  expect(result.alpha.im).toBe(0);
  // Beta should become -1
  expect(result.beta.re).toBe(-1);
  expect(result.beta.im).toBe(0);
});

test("applying Y twice returns the original state (involution)", () => {
  // Y * Y = I. Uses a fully complex state so both channels and both
  // components are exercised; two applications return the exact originals.
  const startAlpha = { re: 0.5, im: 0.5 };
  const startBeta = { re: 0.5, im: -0.5 };
  const once = backend.YGate(startAlpha, startBeta);
  const twice = backend.YGate(once.alpha, once.beta);
  // Alpha should return to 0.5 + 0.5i
  expect(twice.alpha.re).toBe(startAlpha.re);
  expect(twice.alpha.im).toBe(startAlpha.im);
  // Beta should return to 0.5 - 0.5i
  expect(twice.beta.re).toBe(startBeta.re);
  expect(twice.beta.im).toBe(startBeta.im);
});
