import { expect, test } from "vitest";
import backendModule from "../../../compiledBackend/backend.out";
import { sqrt } from "mathjs";
let backend = await backendModule();

// The following tests are generated by claude 4.8 opus (though I have verified them):

// Z = [[1, 0], [0, -1]], so alpha' = alpha (unchanged) and beta' = -beta.
// It is diagonal: no swap, no rotation. Alpha passes through untouched and
// beta is negated (a sign-bit flip on both of its components) -- both exact
// operations, so these use toBe. A near-miss would mean the gate is doing
// real floating-point work it should not be.

// ================================================================
// SECTION 1: Basis states (defining behavior / eigenstates)
// ================================================================

test("results are as expected for the |0> basis state (1, 0)", () => {
  const result = backend.ZGate({ re: 1, im: 0 }, { re: 0, im: 0 });
  // Z|0> = |0> (the +1 eigenstate): nothing changes
  // Alpha should stay 1
  expect(result.alpha.re).toBe(1);
  expect(result.alpha.im).toBe(0);
  // Beta should stay 0
  expect(result.beta.re).toBe(0);
  expect(result.beta.im).toBe(0);
});

test("results are as expected for the |1> basis state (0, 1)", () => {
  const result = backend.ZGate({ re: 0, im: 0 }, { re: 1, im: 0 });
  // Z|1> = -|1> (the -1 eigenstate): beta flips sign
  // Alpha should stay 0
  expect(result.alpha.re).toBe(0);
  expect(result.alpha.im).toBe(0);
  // Beta should become -1
  expect(result.beta.re).toBe(-1);
  expect(result.beta.im).toBe(0);
});

// ================================================================
// SECTION 2: General behavior
// ================================================================

test("results are as expected for a real superposition (0.6, 0.8)", () => {
  const result = backend.ZGate({ re: 0.6, im: 0 }, { re: 0.8, im: 0 });
  // Alpha unchanged, beta negated
  // Alpha should stay 0.6
  expect(result.alpha.re).toBe(0.6);
  expect(result.alpha.im).toBe(0);
  // Beta should become -0.8
  expect(result.beta.re).toBe(-0.8);
  expect(result.beta.im).toBe(0);
});

test("results are as expected for a general complex state with mixed signs ((1 - 2i)/sqrt(30), (-3 + 4i)/sqrt(30))", () => {
  const result = backend.ZGate(
    { re: 1 / sqrt(30), im: -2 / sqrt(30) },
    { re: -3 / sqrt(30), im: 4 / sqrt(30) },
  );
  // alpha' = alpha = (1 - 2i)/sqrt(30)  (both components pass through unchanged)
  // beta'  = -beta = (3 - 4i)/sqrt(30)  (both components negated)
  // Alpha must keep its sign and its imaginary part while beta is fully
  // negated, so negating alpha, partially negating beta, conjugating beta
  // instead of negating it, or swapping the two amplitudes all surface here.
  // Alpha should stay (1 - 2i)/sqrt(30)
  expect(result.alpha.re).toBe(1 / sqrt(30));
  expect(result.alpha.im).toBe(-2 / sqrt(30));
  // Beta should become (3 - 4i)/sqrt(30)
  expect(result.beta.re).toBe(3 / sqrt(30));
  expect(result.beta.im).toBe(-4 / sqrt(30));
});

// ================================================================
// SECTION 3: Edge cases
// ================================================================

test("results are as expected for purely imaginary amplitudes (i/sqrt(2), i/sqrt(2))", () => {
  const result = backend.ZGate(
    { re: 0, im: 1 / sqrt(2) },
    { re: 0, im: 1 / sqrt(2) },
  );
  // Alpha (imaginary) passes through untouched; beta (imaginary) is negated.
  // Confirms beta's imaginary part is negated and alpha's is left alone.
  // Alpha should stay i/sqrt(2)
  expect(result.alpha.re).toBe(0);
  expect(result.alpha.im).toBe(1 / sqrt(2));
  // Beta should become -i/sqrt(2)
  expect(result.beta.re).toBe(0);
  expect(result.beta.im).toBe(-1 / sqrt(2));
});

test("applying Z twice returns the original state (involution)", () => {
  // Z * Z = I. Negating beta twice restores it; alpha never changes.
  const startAlpha = { re: 0.5, im: 0.5 };
  const startBeta = { re: 0.5, im: -0.5 };
  const once = backend.ZGate(startAlpha, startBeta);
  const twice = backend.ZGate(once.alpha, once.beta);
  // Alpha should return to 0.5 + 0.5i
  expect(twice.alpha.re).toBe(startAlpha.re);
  expect(twice.alpha.im).toBe(startAlpha.im);
  // Beta should return to 0.5 - 0.5i
  expect(twice.beta.re).toBe(startBeta.re);
  expect(twice.beta.im).toBe(startBeta.im);
});
