#include <stdio.h>
#include <sys/stat.h>
// include the enscripten library in order to use Embind. emcc will be able to
// find it, even though vscode can not, so don't mind the squiggles.
#include <emscripten/bind.h>

#include <array>
#include <cmath>
#include <complex>
#include <filesystem>
#include <iostream>
#include <limits>
#include <string>

// A struct that makes sending
// complex numbers back and forth
// between c++ and javascript easier.
struct complexReplacement {
  double re;
  double im;
};

// Create a class we can return to our jsx.
class NormClass {
  // Make all the values public
 public:
  double normAmpFactor;
  complexReplacement alphaStruct;
  complexReplacement betaStruct;

  // Make the consturctor
  NormClass(double normAmp, complexReplacement a, complexReplacement b) {
    normAmpFactor = normAmp;
    alphaStruct = a;
    betaStruct = b;
  }

  // Make a default construct to prevent enscripten from getting angry
  NormClass() = default;
};

class AlphaAndBetaClass {
 public:
  complexReplacement alpha;
  complexReplacement beta;

  // Make the constructor
  AlphaAndBetaClass(complexReplacement a, complexReplacement b) {
    alpha = a;
    beta = b;
  }

  // Make a default constructor for enscripten
  AlphaAndBetaClass() = default;
};

// Functions must be "prototyped" in C++ before main, or main will not recognize
// them.
int testJSFunctionality();
NormClass normalizeState(double sqrNormalization,
                         complexReplacement alphaStruct,
                         complexReplacement betaStruct);

std::array<std::complex<double>, 2> matrixVectorMultiplication(
    std::array<std::array<std::complex<double>, 2>, 2> matrix,
    std::array<std::complex<double>, 2> vector);

AlphaAndBetaClass hadamardGate(complexReplacement alphaStruct,
                               complexReplacement betaStruct);

std::complex<double> rowColVectorMult(
    std::array<std::complex<double>, 2> rowVec,
    std::array<std::complex<double>, 2> colVec);

double measurementProbability(std::array<std::complex<double>, 2> basisVector,
                              complexReplacement alphaStruct,
                              complexReplacement betaStruct);

int main() {
  // check the |+> state
  std::array<std::complex<double>, 2> rowVec{(1 / sqrt(2)), 1 / sqrt(2)};
  std::array<std::complex<double>, 2> colVec{(1 / sqrt(3)), (1 / sqrt(3))};
  //::cout << rowColVectorMult(rowVec, colVec);
  // std::cout << "\n";
  //  make an alpha and beta struct complexReplacement.
  //  Remember that complexStruct = {re, im}
  complexReplacement alphaStruct{1 / (sqrt(2)), 0};
  complexReplacement betaStruct{1 / sqrt(2), 0};
  // Call our probability finding function
  // std::cout << measurementProbability(rowVec, alphaStruct, betaStruct);
  return 0;
}

// Register Embind bindings for this translation unit.
// EMSCRIPTEN_BINDINGS(...) is a macro (not a namespace member), so it is not
// written as emscripten::EMSCRIPTEN_BINDINGS.
//
// The name `my_module` is just an arbitrary identifier used to make the
// generated registration code unique; you don't define a variable or object
// called `my_module`. Inside this block you list what C++ functions/classes you
// want exposed to the JS-facing module API (via wrappers generated by
// Emscripten/Embind).
//
// Design note (for this project): keep the JS-facing surface small and expose
// "essential" operations/data, while leaving the heavy QM math in C++.
EMSCRIPTEN_BINDINGS(my_module) {
  // embind all complicated data structures as well.
  // First, embind our complex struct using value object. Make sure to bind
  // its members as well using field.
  emscripten::value_object<complexReplacement>("complexReplacement")
      .field("re", &complexReplacement::re)
      .field("im", &complexReplacement::im);

  // Now embind our norm class using value_object, not class. This means
  // we cant do new NormClass in JS, but we can stll access values like
  // result.alphaStruct.re
  emscripten::value_object<NormClass>("NormClass")
      .field("normAmpFactor", &NormClass::normAmpFactor)
      .field("alphaStruct", &NormClass::alphaStruct)
      .field("betaStruct", &NormClass::betaStruct);
  // Embind our alpha and beta class to return those
  // (could return them through norm, but thats a waste of time)
  emscripten::value_object<AlphaAndBetaClass>("AlphaAndBetaClass")
      .field("alpha", &AlphaAndBetaClass::alpha)
      .field("beta", &AlphaAndBetaClass::beta);

  // Embind the functions last, because it depends on data above.
  // First comes the name of the function as js will see
  // it, and second comes the reference to the actual function in your c++ code.
  emscripten::function("normalizeState", &normalizeState);
  emscripten::function("hadamardGate", &hadamardGate);
}

// The full function that exists for testing js integration
int testJSFunctionality() { return 2 + 3; }

// Normalize the state using sqrNormalization (the squared normalization
// factor). The normalized amplitudes
// (i.e alpha/N) and the normalized probabilities (|alpha|^2/N^2) are NOT the
// same! TODO check for unnecessary calculations and fix sqrNormalization is
// zero error
NormClass normalizeState(double sqrNormalization,
                         complexReplacement alphaStruct,
                         complexReplacement betaStruct) {
  // First, check if sqrNormalization is zero. If it is, figure out a way to
  // deal with this later. This function should not be callable when
  // sqrNormalization is zero, so it should be fine.
  if (std::abs(sqrNormalization) <= 0.000000001) {
    return NormClass(0.0, {0.0, 0.0}, {0.0, 0.0});
  }

  // Make new alpha and beta from the struct complexReplacement to std::complex.
  std::complex<double> alpha(alphaStruct.re, alphaStruct.im);
  std::complex<double> beta(betaStruct.re, betaStruct.im);

  // Next, calculate the sqrt of the squared normalization factor to get the
  // normalize amplitude factor.
  double normAmpFactor = std::sqrt(sqrNormalization);

  // Normalize alpha and beta
  alpha = alpha / normAmpFactor;
  beta = beta / normAmpFactor;
  std::cout << alpha << " normalized and normalized " << beta << std::endl;

  // Now convert them back to structs. Remember, .real() is for complex from
  // std, but our complex struct has the member re (represent the same ideas,
  // just renamed for clarity)
  complexReplacement newAlphaStruct = {alpha.real(), alpha.imag()};
  complexReplacement newBetaStruct = {beta.real(), beta.imag()};

  // add our values to reeturn
  NormClass normalizedValues =
      NormClass(normAmpFactor, newAlphaStruct, newBetaStruct);

  // Return zero to end the function
  return normalizedValues;
}

// Takes in a 2x2 matrix and a (mathematical) vector and multiplies them
// together, giving the output vector. Use std::array instead of generic arrays.
// Its best practice in C++ as they are handled better and have the
// same performance. Vectors would be slightly wasteful here,
// since the size is not dynamic
std::array<std::complex<double>, 2> matrixVectorMultiplication(
    std::array<std::array<std::complex<double>, 2>, 2> matrix,
    std::array<std::complex<double>, 2> vector) {
  // (a b) (x) = (a(x) + b(y))
  // (c d) (y)    (c(x) + d(y))
  // Get those variables and multiply it out.
  // Declaring all of these variables is technically inefficent,
  // as they are only used once. However,
  // it makes the code much more readable, so I
  // am going to leave it unless it causes significant overhead.
  // (also -01 build will optimize it away iiuc)
  std::complex<double> a = matrix[0][0];
  std::complex<double> b = matrix[0][1];
  std::complex<double> c = matrix[1][0];
  std::complex<double> d = matrix[1][1];
  std::complex<double> x = vector[0];
  std::complex<double> y = vector[1];
  // Every std::array needs an extra set of braces
  // because std::array is a wrapper
  std::array<std::complex<double>, 2> resultVector = {
      {(a * x + b * y), (c * x + d * y)}};
  return resultVector;
}

// A function that takes in a row vector and a col vector
// and multiplies them together. Usually, the row vector will be
// the bases for calculating probability (i.e. <0| = (0,1))
// while the col vector will be the normalized state. Returns
// a scalar (usually the probability amplitude), which can be a complex,
// so return a complex double. This DOES NOT calculate the probability,
// just the probability amplitude.
std::complex<double> rowColVectorMult(
    std::array<std::complex<double>, 2> rowVec,
    std::array<std::complex<double>, 2> colVec) {
  // For a 1x2 times 2x1, the calculation is
  // (a, b) * (x)   = (a*x) + (b*y)
  //          (y)

  // return the result of the multiplication
  return (rowVec[0] * colVec[0]) + (rowVec[1] * colVec[1]);
}

// A function to return the probability of collapse of the current 2 state
// system to a specific basis state, given that a measurement in this
// basis is performed.
// Remember: basis is the whole set of states/vectors (i.e. {|0>,|1>}),
// while the basis state is one of the states/vectors of that basis.
// The basis state must be provided in it its vector form
// (row or column doesn't technically matter. I mean, you could
// make it a column vector by having a 2d array of 1 element each,
// but im going to assume a 1d array of 2 elements), and not its bra/ket
// form. It returns the probability in terms of double, since
// the probability must be a real number.
double measurementProbability(std::array<std::complex<double>, 2> basisVector,
                              complexReplacement alphaStruct,
                              complexReplacement betaStruct) {
  // converting alpha and beta into a single std::array of complex doubles
  // (the states vector form).

  // Start by making alpha and beta into complex values
  std::complex alpha(alphaStruct.re, alphaStruct.im);
  std::complex beta(betaStruct.re, betaStruct.im);

  // Now, make a state vector with them
  std::array<std::complex<double>, 2> stateVector{alpha, beta};
  // Multiply the 2 vectors together using the function rowColVecMult.
  // Remember that the basis vector is first so it goes in
  // as the row vector, and the state vector is second so it acts
  // as the column vector. This is the probability amplitude
  std::complex<double> probabilityAmplitude =
      rowColVectorMult(basisVector, stateVector);

  // The probability is found by taking magnitude squared of the
  // probability amplitude, i.e: |amp|^2. For any value a,
  // |a|^2 = aa*, where a* = (a.real, a.im * -1). So, calculate
  // the probability amplitude squared as amp * (amp.real(), amp.im * - 1).
  // This is guaranteed to be a real number, but the compiler doesn't know that,
  // so we must first make it into a complex number.
  std::complex<double> probSquared =
      (probabilityAmplitude *
       std::complex<double>{probabilityAmplitude.real(),
                            probabilityAmplitude.imag() * -1});

  // Manually return only the real part of probSquared (probSquared.imag == 0
  // anyways)
  return probSquared.real();
}

// A function that takes in the alpha and beta magnitudes and computes
// the resulting transformation of applying the hadamard gate to that
// qubit. Returns alpha and beta to the caller in the form of an object
// that holds the complex replacement structs (similar to normalize state).
// Alpha and beta must be defined as complexReplacement to start,
// or js can not pass them in properly (see norm function for why).
AlphaAndBetaClass hadamardGate(complexReplacement alphaStruct,
                               complexReplacement betaStruct) {
  // Define the matrix for the hadamard gate
  // (Every std::array needs an extra set of braces
  // because std::array is a wrapper).
  // First, convert the gates values into complex value of 1/sqrt
  std::complex<double> hadValues(1 / std::sqrt(2), 0);
  // Now create the matrix. Standard form is:
  // (1/sqrt(2)) (1, 1)
  //             (1, -1), but you can distribute the 1/sqrt(2) through
  std::array<std::array<std::complex<double>, 2>, 2> hadMatrix = {
      {{hadValues, hadValues}, {hadValues, -hadValues}}};

  // Get the alpha and beta structs into std::complex as
  // complex multiplication is built into std::complex
  std::complex alpha(alphaStruct.re, alphaStruct.im);
  std::complex beta(betaStruct.re, betaStruct.im);

  // alpha and beta are scalars associated with |0> aka (1 0)^T,
  // |1> aka (0 1)^T. So, write out their full matrix forms
  std::array<std::complex<double>, 2> zeroVector = {
      {alpha, std::complex<double>(0.0, 0.0)}};

  std::array<std::complex<double>, 2> oneVector = {
      {std::complex<double>(0.0, 0.0), beta}};

  // Calculate the matrix-vector multiplication for each
  std::array<std::complex<double>, 2> hadAppliedToZero =
      matrixVectorMultiplication(hadMatrix, zeroVector);
  std::array<std::complex<double>, 2> hadAppliedToOne =
      matrixVectorMultiplication(hadMatrix, oneVector);

  // Add the two resulting vectors together
  std::array<std::complex<double>, 2> resultVector = {
      {hadAppliedToZero[0] + hadAppliedToOne[0],
       hadAppliedToZero[1] + hadAppliedToOne[1]}};

  // Make the two vectors into their corresponding alpha and beta.
  // The top row (row 0) is the magnitude of alpha, because it
  // corresponds to (1,0)^T. The bottom row (row 1) is the magnitude
  // of alpha, as it corresponds to (0,1)^T.
  // Get the imaginary and real values out of std::complex using .real()
  // and .imag()
  complexReplacement alphaToReturn = {resultVector[0].real(),
                                      resultVector[0].imag()};
  complexReplacement betaToReturn = {resultVector[1].real(),
                                     resultVector[1].imag()};
  // Make our alpha and beta class that we will return
  AlphaAndBetaClass resultVals = AlphaAndBetaClass(alphaToReturn, betaToReturn);

  return resultVals;
}