#include <stdio.h>
#include <sys/stat.h>
// include the enscripten library in order to use Embind. emcc will be able to
// find it, even though vscode can not, so don't mind the squiggles.
#include <emscripten/bind.h>

#include <array>
#include <cmath>
#include <complex>
#include <filesystem>
#include <iostream>
#include <limits>
#include <numbers>
#include <string>

// A struct that makes sending
// complex numbers back and forth
// between c++ and javascript easier.
struct complexReplacement {
  double re;
  double im;
};

// Create a class we can return to our jsx.

class AlphaAndBetaClass {
 public:
  complexReplacement alpha;
  complexReplacement beta;

  // Make the constructor
  AlphaAndBetaClass(complexReplacement a, complexReplacement b) {
    alpha = a;
    beta = b;
  }

  // Make a default constructor for enscripten
  AlphaAndBetaClass() = default;
};

// Functions must be "prototyped" in C++ before main, or main will not recognize
// them.
int testJSFunctionality();

std::array<std::complex<double>, 2> matrixVectorMultiplication(
    std::array<std::array<std::complex<double>, 2>, 2> matrix,
    std::array<std::complex<double>, 2> vector);

AlphaAndBetaClass hadamardGate(complexReplacement alphaStruct,
                               complexReplacement betaStruct);
AlphaAndBetaClass XGate(complexReplacement alphaStruct,
                        complexReplacement betaStruct);
AlphaAndBetaClass YGate(complexReplacement alphaStruct,
                        complexReplacement betaStruct);
AlphaAndBetaClass ZGate(complexReplacement alphaStruct,
                        complexReplacement betaStruct);
AlphaAndBetaClass TGate(complexReplacement alphaStruct,
                        complexReplacement betaStruct);
AlphaAndBetaClass SGate(complexReplacement alphaStruct,
                        complexReplacement betaStruct);

std::complex<double> rowColVectorMult(
    std::array<std::complex<double>, 2> rowVec,
    std::array<std::complex<double>, 2> colVec);

double measurementProbability(
    std::vector<complexReplacement> basisVectorReplacement,
    complexReplacement alphaStruct, complexReplacement betaStruct);

int main() {
  // check the |+> state
  std::array<std::complex<double>, 2> rowVec{(1 / sqrt(2)), 1 / sqrt(2)};
  std::array<std::complex<double>, 2> colVec{(1 / sqrt(3)), (1 / sqrt(3))};
  //::cout << rowColVectorMult(rowVec, colVec);
  // std::cout << "\n";
  //  make an alpha and beta struct complexReplacement.
  //  Remember that complexStruct = {re, im}
  complexReplacement alphaStruct{1 / (sqrt(2)), 0};
  complexReplacement betaStruct{1 / sqrt(2), 0};
  // Call our probability finding function
  // std::cout << measurementProbability(rowVec, alphaStruct, betaStruct);
  return 0;
}

// Register Embind bindings for this translation unit.
// EMSCRIPTEN_BINDINGS(...) is a macro (not a namespace member), so it is not
// written as emscripten::EMSCRIPTEN_BINDINGS.
//
// The name `my_module` is just an arbitrary identifier used to make the
// generated registration code unique; you don't define a variable or object
// called `my_module`. Inside this block you list what C++ functions/classes you
// want exposed to the JS-facing module API (via wrappers generated by
// Emscripten/Embind).
//
// Design note (for this project): keep the JS-facing surface small and expose
// "essential" operations/data, while leaving the heavy QM math in C++.
EMSCRIPTEN_BINDINGS(my_module) {
  // embind all complicated data structures as well.
  // First, embind our complex struct using value object. Make sure to bind
  // its members as well using field.
  emscripten::value_object<complexReplacement>("complexReplacement")
      .field("re", &complexReplacement::re)
      .field("im", &complexReplacement::im);

  // Embind our array of complex replacement. Must be a vector
  // because complex is a struct and emscripten can't handle binding
  // arrays of structs as far as I can tell
  emscripten::register_vector<complexReplacement>("ComplexReplacementArray");

  // Embind our alpha and beta class to return alpha and beta.
  // embinding the class means we cant make a new alphaandbetaclass
  // in js, but we can stll access values like
  // result.alpha
  // (could return them through norm, but thats a waste of time)
  emscripten::value_object<AlphaAndBetaClass>("AlphaAndBetaClass")
      .field("alpha", &AlphaAndBetaClass::alpha)
      .field("beta", &AlphaAndBetaClass::beta);

  // Embind the functions last, because it depends on data above.
  // First comes the name of the function as js will see
  // it, and second comes the reference to the actual function in your c++ code.
  emscripten::function("measurementProbability", &measurementProbability);
  emscripten::function("hadamardGate", &hadamardGate);
  emscripten::function("XGate", &XGate);
  emscripten::function("YGate", &YGate);
  emscripten::function("ZGate", &ZGate);
  emscripten::function("SGate", &SGate);
  emscripten::function("TGate", &TGate);
}

// The full function that exists for testing js integration
int testJSFunctionality() { return 2 + 3; }

// Takes in a 2x2 matrix and a (mathematical) vector and multiplies them
// together, giving the output vector. Use std::array instead of generic arrays.
// Its best practice in C++ as they are handled better and have the
// same performance. Vectors would be slightly wasteful here,
// since the size is not dynamic
std::array<std::complex<double>, 2> matrixVectorMultiplication(
    std::array<std::array<std::complex<double>, 2>, 2> matrix,
    std::array<std::complex<double>, 2> vector) {
  // (a b) (x) = (a(x) + b(y))
  // (c d) (y)    (c(x) + d(y))
  // Get those variables and multiply it out.
  // Declaring all of these variables is technically inefficent,
  // as they are only used once. However,
  // it makes the code much more readable, so I
  // am going to leave it unless it causes significant overhead.
  // (also -01 build will optimize it away iiuc)
  std::complex<double> a = matrix[0][0];
  std::complex<double> b = matrix[0][1];
  std::complex<double> c = matrix[1][0];
  std::complex<double> d = matrix[1][1];
  std::complex<double> x = vector[0];
  std::complex<double> y = vector[1];
  // Every std::array needs an extra set of braces
  // because std::array is a wrapper
  std::array<std::complex<double>, 2> resultVector = {
      {(a * x + b * y), (c * x + d * y)}};
  return resultVector;
}

// A function that takes in a row vector and a col vector
// and multiplies them together. Usually, the row vector will be
// the bases for calculating probability (i.e. <0| = (0,1))
// while the col vector will be the normalized state. Returns
// a scalar (usually the probability amplitude), which can be a complex,
// so return a complex double. This DOES NOT calculate the probability,
// just the probability amplitude.
std::complex<double> rowColVectorMult(
    std::array<std::complex<double>, 2> rowVec,
    std::array<std::complex<double>, 2> colVec) {
  // For a 1x2 times 2x1, the calculation is
  // (a, b) * (x)   = (a*x) + (b*y)
  //          (y)

  // return the result of the multiplication
  return (rowVec[0] * colVec[0]) + (rowVec[1] * colVec[1]);
}

// A function to return the probability of collapse of the current 2 state
// system to a specific basis state, given that a measurement in this
// basis is performed.
// Remember: basis is the whole set of states/vectors (i.e. {|0>,|1>}),
// while the basis state is one of the states/vectors of that basis.
// The basis state must be provided in it its vector form
// (row or column doesn't technically matter. I mean, you could
// make it a column vector by having a 2d array of 1 element each,
// but im going to assume a 1d array of 2 elements), and not its bra/ket
// form. It returns the probability in terms of double, since
// the probability must be a real number.
// the arrays hold complex replacements, since that is how we pass
// complex between js and C++.
double measurementProbability(
    std::vector<complexReplacement> basisVectorReplacement,
    complexReplacement alphaStruct, complexReplacement betaStruct) {
  // converting alpha and beta into a single std::array of complex doubles
  // (the states vector form).

  // Start by making alpha and beta into complex values
  std::complex alpha(alphaStruct.re, alphaStruct.im);
  std::complex beta(betaStruct.re, betaStruct.im);

  // Now, make a state vector with them
  std::array<std::complex<double>, 2> stateVector{alpha, beta};

  // Convert the array of complex replacements into the basis vector
  std::complex zeroth(basisVectorReplacement[0].re,
                      basisVectorReplacement[0].im);
  std::complex first(basisVectorReplacement[1].re,
                     basisVectorReplacement[1].im);

  std::array<std::complex<double>, 2> basisVector{zeroth, first};
  // Multiply the 2 vectors together using the function rowColVecMult.
  // Remember that the basis vector is first so it goes in
  // as the row vector, and the state vector is second so it acts
  // as the column vector. This is the probability amplitude
  std::complex<double> probabilityAmplitude =
      rowColVectorMult(basisVector, stateVector);

  // The probability is found by taking magnitude squared of the
  // probability amplitude, i.e: |amp|^2. For any value a,
  // |a|^2 = aa*, where a* = (a.real, a.im * -1). So, calculate
  // the probability amplitude squared as amp * (amp.real(), amp.im * - 1).
  // This is guaranteed to be a real number, but the compiler doesn't know that,
  // so we must first make it into a complex number.
  std::complex<double> probSquared =
      (probabilityAmplitude *
       std::complex<double>{probabilityAmplitude.real(),
                            probabilityAmplitude.imag() * -1});

  // Manually return only the real part of probSquared (probSquared.imag == 0
  // anyways)
  return probSquared.real();
}

// Applying gates has a lot of repeated work. This helper funciton generalizes
// this work. Takes the complex replacement for alpha and beta, as well as the
// particular gates matrix form, and returns our qubit with the gate applied to
// it in the alphaAndBetaClass form.
AlphaAndBetaClass gateApplyHelper(
    complexReplacement alphaStruct, complexReplacement betaStruct,
    std::array<std::array<std::complex<double>, 2>, 2> gateMatrix) {
  // Get the alpha and beta structs into std::complex as
  // complex multiplication is built into std::complex
  std::complex alpha(alphaStruct.re, alphaStruct.im);
  std::complex beta(betaStruct.re, betaStruct.im);

  // alpha and beta are scalars associated with |0> aka (1 0)^T,
  // |1> aka (0 1)^T. So, write out their full matrix forms
  std::array<std::complex<double>, 2> zeroVector = {
      {alpha, std::complex<double>(0.0, 0.0)}};

  std::array<std::complex<double>, 2> oneVector = {
      {std::complex<double>(0.0, 0.0), beta}};

  // Calculate the matrix-vector multiplication for each
  std::array<std::complex<double>, 2> gateAppliedToZero =
      matrixVectorMultiplication(gateMatrix, zeroVector);
  std::array<std::complex<double>, 2> gateAppliedToOne =
      matrixVectorMultiplication(gateMatrix, oneVector);

  // Add the two resulting vectors together
  std::array<std::complex<double>, 2> resultVector = {
      {gateAppliedToZero[0] + gateAppliedToOne[0],
       gateAppliedToZero[1] + gateAppliedToOne[1]}};

  // Make the two vectors into their corresponding alpha and beta.
  // The top row (row 0) is the magnitude of alpha, because it
  // corresponds to (1,0)^T. The bottom row (row 1) is the magnitude
  // of alpha, as it corresponds to (0,1)^T.
  // Get the imaginary and real values out of std::complex using .real()
  // and .imag()
  complexReplacement alphaToReturn = {resultVector[0].real(),
                                      resultVector[0].imag()};
  complexReplacement betaToReturn = {resultVector[1].real(),
                                     resultVector[1].imag()};
  // Make our alpha and beta class that we will return
  AlphaAndBetaClass resultVals = AlphaAndBetaClass(alphaToReturn, betaToReturn);

  // return this to the calling gate function
  return resultVals;
}

// A function that takes in the alpha and beta magnitudes and computes
// the resulting transformation of applying the hadamard (H) gate to that
// qubit. Returns alpha and beta to the caller in the form of an object
// that holds the complex replacement structs (similar to normalize state).
// Alpha and beta must be defined as complexReplacement to start,
// or js can not pass them in properly (see norm function for why).
AlphaAndBetaClass hadamardGate(complexReplacement alphaStruct,
                               complexReplacement betaStruct) {
  // Define the matrix for the hadamard gate
  // (Every std::array needs an extra set of braces
  // because std::array is a wrapper).
  // First, convert the gates values into complex value of 1/sqrt
  std::complex<double> hadValues(1.0 / std::sqrt(2.0), 0.0);
  // Now create the matrix. Standard form is:
  // (1/sqrt(2)) (1, 1)
  //             (1, -1), but you can distribute the 1/sqrt(2) through
  std::array<std::array<std::complex<double>, 2>, 2> hadMatrix = {
      {{hadValues, hadValues}, {hadValues, -hadValues}}};

  // Call gate apply helper and return the resulting AlphaAndBetaClass struct
  return gateApplyHelper(alphaStruct, betaStruct, hadMatrix);
}

// A function that applies the X (pauli x) gate to our qubit.
AlphaAndBetaClass XGate(complexReplacement alphaStruct,
                        complexReplacement betaStruct) {
  // Create the matrix. Standard form is:
  // (0, 1)
  // (1, 0)
  std::array<std::array<std::complex<double>, 2>, 2> XMatrix = {
      {{std::complex(0.0, 0.0), std::complex(1.0, 0.0)},
       {std::complex(1.0, 0.0), std::complex(0.0, 0.0)}}};

  // Call gate apply helper and return the resulting AlphaAndBetaClass struct
  return gateApplyHelper(alphaStruct, betaStruct, XMatrix);
}

// Applies the Y (pauli y) gate to our qubit
AlphaAndBetaClass YGate(complexReplacement alphaStruct,
                        complexReplacement betaStruct) {
  // Create the matrix. Standard form is:
  // (0, -i)
  // (i, 0)
  // Complex is complex(real, imag)

  // Add them to the matrix
  std::array<std::array<std::complex<double>, 2>, 2> YMatrix = {
      {{std::complex(0.0, 0.0), std::complex(0.0, -1.0)},
       {std::complex(0.0, 1.0), std::complex(0.0, 0.0)}}};

  // Call gate apply helper and return the resulting AlphaAndBetaClass struct
  return gateApplyHelper(alphaStruct, betaStruct, YMatrix);
}

// Applies the z (pauli z) gate to our qubit
AlphaAndBetaClass ZGate(complexReplacement alphaStruct,
                        complexReplacement betaStruct) {
  // Create the matrix. Standard form is:
  // (1, 0)
  // (0, -1)
  std::array<std::array<std::complex<double>, 2>, 2> ZMatrix = {
      {{std::complex(1.0, 0.0), std::complex(0.0, 0.0)},
       {std::complex(0.0, 0.0), std::complex(-1.0, 0.0)}}};

  // Call gate apply helper and return the resulting AlphaAndBetaClass struct
  return gateApplyHelper(alphaStruct, betaStruct, ZMatrix);
}

// Applies the S phase gate to our qubit
AlphaAndBetaClass SGate(complexReplacement alphaStruct,
                        complexReplacement betaStruct) {
  // Create the matrix. Standard form is:
  // (1, 0)
  // (0, i)
  std::array<std::array<std::complex<double>, 2>, 2> SMatrix = {
      {{std::complex(1.0, 0.0), std::complex(0.0, 0.0)},
       {std::complex(0.0, 0.0), std::complex(0.0, 1.0)}}};

  // Call gate apply helper and return the resulting AlphaAndBetaClass struct
  return gateApplyHelper(alphaStruct, betaStruct, SMatrix);
}

// Applies the T phase gate to our qubit
AlphaAndBetaClass TGate(complexReplacement alphaStruct,
                        complexReplacement betaStruct) {
  // Create the matrix. Standard form is:
  // (1, 0)
  // (0, e^(ipi/4))
  // make the complex value for e^ipi/4 explicitly
  std::complex<double> bottomRight =
      std::exp(std::complex<double>(0.0, (std::numbers::pi) / 4.0));

  std::array<std::array<std::complex<double>, 2>, 2> TMatrix = {
      {{std::complex(1.0, 0.0), std::complex(0.0, 0.0)},
       {std::complex(0.0, 0.0), bottomRight}}};

  // Call gate apply helper and return the resulting AlphaAndBetaClass struct
  return gateApplyHelper(alphaStruct, betaStruct, TMatrix);
}